### ISSUE TITLE
Search in readable content is unreliable

### ISSUE THREAD

**Issue by MageSlayer** [go-shiori/shiori#722]
## Data
- 1.5.5
- SQLite(???). I did nothing to setup 
- Devuan x64 
- Web interface  

## Describe the bug / actual behavior
Search in readable content is unreliable.

## Expected behavior
Each & every work in readable content should be searchable.

## To Reproduce
1. Create "https://thehealthylife.com/" bookmark with archived content.
2. Look into readable content. See word "Markus" at the end of text.
3. Try searching for Markus
4. Observe "No saved bookmarks yet :("

## Screenshots
NA

## Notes
NA

**Comment by fmartingr** [comment]
This may get fixed with #721, I've made some tests and it shows me results from readable content.

**Comment by MageSlayer** [comment]
Do you have any "nightly"/"master" builds available to test?

**Comment by fmartingr** [comment]
> Do you have any "nightly"/"master" builds available to test?

I plan to do a release candidate for 1.6.0 when #721 is merged. 

In the meanwhile, latest commit on master is always built over the `dev` tag on docker and you can access the latest build binaries from the action artifacts: https://github.com/go-shiori/shiori/actions/runs/5918425180

Remember to backup your database if you plan to test development builds.

**Comment by MageSlayer** [comment]
I've tested using that artifact.
Still the same behavior => bookmark not found.

**Comment by MageSlayer** [comment]
Tested using https://github.com/go-shiori/shiori/releases/tag/v1.6.0-rc.1
Still the same issue.
